apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: businesslens-monitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: businesslens
  namespaceSelector:
    matchNames:
      - businesslens
  endpoints:
    - port: http
      path: /metrics
      interval: 15s