apiVersion: v1
kind: Service
metadata:
  name: businesslens-web
  namespace: businesslens
  labels:
    app: businesslens
    tier: frontend
spec:
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: web
  selector:
    app: businesslens
    tier: frontend
status:
  loadBalancer:
    ingress:
      - ip: <external-ip>
```
